### ISSUE TITLE
Add units for precipitation

### ISSUE THREAD

**Issue by AdamRJensen** [AssessingSolar/dtu_solar_station#10]

**Comment by IoannisSifnaios** [comment]
From this [report](https://orbit.dtu.dk/files/142165992/Untitled.pdf):

<img width="554" alt="image" src="https://github.com/AssessingSolar/dtu_solar_station/assets/88548539/8a57e0fc-aff6-4c87-8e06-b71a25e22deb">

<img width="552" alt="image" src="https://github.com/AssessingSolar/dtu_solar_station/assets/88548539/463ac2f7-bee5-4aba-8d1b-fcaa45818b49">
